mobileRobot:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  # Position controller 
  left_b_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_b
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_m_position_controller:
   type: effort_controllers/JointPositionController
   joint: left_m
   pid: {p: 100.0, i: 0.01, d: 10.0}
  left_f_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_f
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_b_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_b
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_m_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_m
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_f_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_f
    pid: {p: 100.0, i: 0.01, d: 10.0}
